config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "home#index"

  resources :users do
    resources :categories do
      resources :expenses
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categories_expense.rb
class CategoriesExpense < ApplicationRecord
  belongs_to :category
  belongs_to :expense
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :categories_expenses, dependent: :destroy
  has_many :expenses, through: :categories_expenses, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :category
  has_many :categories_expenses, dependent: :destroy
  has_many :categories, through: :categories_expenses

  validates :name, presence: true
  validates :amount, presence: true
  validates :author_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :expenses, foreign_key: :author_id

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :root_path
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :current_user

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(_resource)
    user_categories_path(current_user)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # This before_action ensures that the set_user method is called before any other actions in this controller.
  before_action :set_user

  # GET /users/:user_id/categories
  def index
    # Retrieves all categories and assigns them to the instance variable @categories.
    @categories = Category.includes(:expenses).all
    @category_totals = {}

    @categories.each do |category|
      @category_id = category.id
      @expenses = @user.expenses.includes(:category).where(category: @category_id)
      @category_totals[@category_id] = @expenses.sum(:amount)
    end
  end

  # GET /users/:user_id/categories/new
  def new
    # Initializes a new category instance to be used in the 'new' view.
    @category = Category.new
  end

  # POST /users/:user_id/categories
  def create
    # Builds a new category associated with the current user and populates it with the submitted parameters.
    @category = @user.categories.new(category_params)

    # Saves the category and handles the redirection based on the outcome.
    if @category.save
      redirect_to user_categories_path(@user), notice: 'Category was successfully created.'
    else
      # If saving fails, renders the 'new' view to display error messages.
      render :new
    end
  end

  private

  # Defines the allowed parameters for category creation.
  def category_params
    params.require(:category).permit(:name, :icon)
  end

  # Finds the user based on the :user_id parameter from the request.
  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  # GET /users/:user_id/categories/:category_id/expenses
  def index
    # Finds the user based on the :user_id parameter from the request.
    @user = User.find(params[:user_id])

    # Finds the category based on the :category_id parameter from the request.
    @category = Category.find(params[:category_id])

    # Retrieves expenses associated with the specified user and category, including the category information.
    @expenses = @user.expenses.includes(:category).where(category: @category)
  end

  # GET /users/:user_id/categories/:category_id/expenses/new
  def new
    # Finds the user based on the :user_id parameter from the request.
    @user = User.find(params[:user_id])

    # Finds the category based on the :category_id parameter from the request.
    @category = Category.find(params[:category_id])

    # Initializes a new expense instance to be used in the 'new' view.
    @expense = Expense.new

    # Retrieves all categories to be used for dropdown selection in the 'new' view.
    @categories = Category.all
  end

  # POST /users/:user_id/categories/:category_id/expenses
  def create
    # Finds the user based on the :user_id parameter from the request.
    @user = User.find(params[:user_id])

    # Finds the category based on the category_id submitted in the expense parameters.
    @category = Category.find(params[:expense][:category_id])

    # Builds a new expense associated with the selected category and populates it with the submitted parameters.
    @expense = @category.expenses.build(expense_params)

    # Sets the author of the expense to the current user.
    @expense.author = @user

    # Saves the expense and handles the redirection based on the outcome.
    if @expense.save
      redirect_to user_category_expenses_path(@user, @category), notice: 'Expense was successfully created.'
    else
      # If saving fails, retrieves all categories to be used for dropdown selection in the 'new' view.
      @categories = Category.all

      # Renders the 'new' view to display error messages.
      render :new
    end
  end

  private

  # Defines the allowed parameters for expense creation.
  def expense_params
    params.require(:expense).permit(:name, :amount, :transaction_date, :category_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # home page
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<header>
    <!-- Menu icon (Hamburger menu) -->
    <p class="menu-icon">&#9776;</p>
    
    <!-- Title for the page -->
    <h2>CATEGORIES</h2>
    
    <!-- Search icon using Font Awesome -->
    <i class="fa fa-search"></i>
</header>

<div class="category-list">
  <!-- Loop through each category in @categories -->
  <% @categories.each do |category| %>
    <%= link_to user_category_expenses_path(@user, category), class: "category-link" do %>
      <!-- Category container -->
      <div class="category">
        <!-- Category icon -->
        <div class="category-icon">
          <img src="<%= category.icon %>" alt="<%= category.name %>">
        </div>
        
        <!-- Category name and creation date -->
        <div>
          <p class="name"><%= category.name %></p>
          <p class="expense-date"><%= category.created_at.strftime("%m/%d/%Y") %></p>
        </div>
        
        <!-- Total expense amount for the category -->
        <div class="amount">
          <p>$ <%= @category_totals[category.id] || 0 %></p>
        </div>
      </div>
    <% end %>
  <% end %>
    <!-- Link to add a new category -->
    <%= link_to new_user_category_path(@user), class: "add-category-btn" do %>
      <span>Add Category</span>
    <% end %>
</div>

app/views/categories/new.html.erb
<header>
  <!-- Link to navigate back to user categories page -->
  <%= link_to user_categories_path(@user), class: "back-icon" do %>
    <!-- Back icon (could be an icon or text) -->
  <% end %>
  
  <!-- Heading for the current page -->
  <h2 class="heading">ADD CATEGORY</h2>
</header>

<!-- Container for the category form -->
<div class='category-list'>
  <div class="form">
    <!-- Form for creating a new category -->
    <%= form_with(model: [@user, @category], local: true, method: :post) do |f| %>
      <!-- Field for category name -->
      <div>
        <%= f.label :name %> <br />
        <%= f.text_field :name, autocomplete: "off" %>
      </div>
      
      <!-- Field for category icon -->
      <div>
        <%= f.label :icon %> <br />
        <%= f.text_field :icon %>
      </div>
      
      <!-- Submission button to save the category -->
      <div>
        <%= f.submit "Save", class: "button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/expenses/index.html.erb
<!-- Header section -->
<header>
  <!-- Link to navigate back to user categories page with a back icon -->
  <%= link_to user_categories_path(@user), class: "back-icon" do %>
    <!-- Back icon (could be an icon or text) -->
  <% end %>
  
  <!-- Heading for the current page with the name of the category -->
  <h2><%= @category.name %></h2>
  
  <!-- Display the total amount of expenses for the category -->
  <p>$ <%= @expenses.sum(:amount) %></p>
</header>

<!-- Container for the list of expenses -->
<div class='category-list'>
  
  <!-- Loop through each expense in @expenses -->
  <% @expenses.each do |expense| %>
  
    <!-- Expense item container -->
    <div class="expense-item">
      
      <!-- Sub-container for expense details -->
      <div>
        <!-- Display the name of the expense -->
        <p><%= expense.name %></p>
        
        <!-- Display the creation date of the expense -->
        <p class="expense-date"><%= expense.created_at.strftime("%m/%d/%Y") %></p>
      </div>
      
      <!-- Display the amount of the expense -->
      <p class="amount">$<%= expense.amount %></p>
      
      <!-- Display the category name of the expense -->
      <p><%= expense.category.name %></p>
    </div>
    
  <% end %>
  
  <!-- Link to add a new transaction for the current category -->
  <%= link_to new_user_category_expense_path(@user, @category), class: "add-transaction" do %>
    <!-- Text for adding a new transaction -->
    <span>Add Transaction</span>
  <% end %>
</div>

app/views/expenses/new.html.erb
<!-- Header section -->
<header>
  <!-- Link to navigate back to the category expenses page with a back icon -->
  <%= link_to user_category_expenses_path(@user, @category), class: "back-icon" do %>
    <!-- Back icon (could be an icon or text) -->
  <% end %>
  
  <!-- Heading for the current page -->
  <h2>NEW TRANSACTION</h2>
  
  <!-- Search icon using Font Awesome -->
  <i class="fa fa-search"></i>
</header>

<!-- Container for the form -->
<div class='category-list'>
  <div class="form">
    
    <!-- Form for creating a new transaction -->
    <%= form_with(model: [@user, @category, @expense], local: true) do |f| %>
      
      <!-- Field for the name of the transaction -->
      <div>
        <%= f.label :name %> <br />
        <%= f.text_field :name, autocomplete: "off" %>
      </div>
      
      <!-- Field for the amount of the transaction -->
      <div>
        <%= f.label :amount %> <br />
        <%= f.text_field :amount %>
      </div>
      
      <!-- Dropdown for selecting the category of the transaction -->
      <%= f.label :category_id %>
      <%= f.collection_select :category_id, @categories, :id, :name %> <br />
      
      <!-- Submission button to save the transaction -->
      <%= f.submit "Save", class: "button" %>
      
    <% end %>
  
  </div>
</div>

app/views/home/index.html.erb
<!-- Main content container -->
<div class="main">
    
    <!-- Footer section -->
    <footer>
        
        <!-- Link to navigate to the login page -->
        <%= link_to "LOGIN", new_user_session_path, id: "login" %>
        
        <!-- Link to navigate to the sign-up page -->
        <%= link_to "SIGN UP", new_user_registration_path, id: "signup" %>
    </footer>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="app-container">
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    </div>

  </body>
</html>